baseline:
  name: HRRR
  template: https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrrr.{yyyymmdd}/conus/hrrr.t{hh}z.wrfprsf{ff}.grib2
cycles:
  start: "2024-04-01T02:00:00"
  step: "01:00:00"
  stop: "2024-04-07T23:00:00"
forecast:
  name: GraphHRRR
  path: /path/to/forecast.zarr
leadtimes:
  start: "01:00:00"
  step: "01:00:00"
  stop: "01:00:00"
meta:
  levels: &levels [200, 300, 475, 800, 825, 850, 875, 900, 925, 950, 975, 1000]
plot:
  baseline: true
threads: 0
variables:
  HGT:
    level_type: isobaricInhPa
    levels: *levels
    standard_name: gh
  REFC:
    level_type: atmosphere
    standard_name: refc
  SPFH:
    level_type: isobaricInhPa
    levels: *levels
    standard_name: q
  T2M:
    level_type: heightAboveGround
    levels: [2]
    standard_name: 2t
  TMP:
    level_type: isobaricInhPa
    levels: *levels
    standard_name: t
  UGRD:
    level_type: isobaricInhPa
    levels: *levels
    standard_name: u
  VGRD:
    level_type: isobaricInhPa
    levels: *levels
    standard_name: v
  VVEL:
    level_type: isobaricInhPa
    levels: *levels
    standard_name: w
workdir: /path/to/workdir/
